<?php

return [
    'sm' => "text-sm",
    'md' => "text-base",
    'lg' => "text-lg",
    'xl' => "text-xl",
    '2xl' => "text-2xl",
    '3xl' => "text-3xl",
    '4xl' => "text-4xl",
    '5xl' => "text-5xl",
    '6xl' => "text-6xl",
    'center' => "text-center",
    'left' => "text-left",
    'right' => "text-right",
    'wrap' => "text-wrap",
    'nowrap' => "text-nowrap",
    'balance' => "text-balance",
    'pretty' => "text-pretty",
    'inherit' => "text-inherit",
    'transparent' => "text-transparent",
    'current' => "text-current",
    'uppercase' => "uppercase",
    'lowercase' =>  "lowercase",
    'capitalize' => "capitalize",
    'normal-case' => "normal-case",

    'truncate' => "truncate",
    'underline' => "underline",
    'no-underline' => "no-underline",
    'line-through' => "line-through",
];